### ISSUE TITLE
Finder crashes when copying files

### ISSUE THREAD

**Issue by itsTyrion** [w0lfschild/DoctorDark#18]
First: Great work overall. I am experiencing the following bug though: copying files to another directory sometimes crashes Finder. copying a .app File to the Applications folder causes it to crash in 10/10 tries, blacklisting finder instantly fixes the problem, but then it flashbangs me again when it is night ;) 
Providing logs, in case you tell me how, is not a problem of course.

**Comment by oc-tk** [comment]
Any progress with this? Yea I know that we are living in 2019 and there is Mojave + Catalina but some people can't afford new MacBook so they are stuck with their 2011 beast.
Could I except any future updates with bug fixes?

**Comment by itsTyrion** [comment]
@Spamm3r you could use the command 
`defaults write -g NSWindowDarkChocolate -bool TRUE` (FALSE to disable) to enable the beta-dark mode in High Sierra, just disable Finder in DoctorDark. You need to use list view, though. (which is not a problem for me, I prefer list view anyways)
