### ISSUE TITLE
Spotlight and Spotlight Menu icon is permanently dark, how to reset this?

### ISSUE THREAD

**Issue by sidpagariya** [w0lfschild/DoctorDark#2]
Hello! After I applied Doctor Dark changes, Spotlight menu item is dark...
How can I blacklist spotlight?
Thanks!

**Comment by w0lfschild** [comment]
I need to look into this. I'm not sure if the blacklisting is working properly but you would want to blacklist 

`SystemUIServer` and not `Spotlight`

**Comment by sidpagariya** [comment]
Ok! Thank you very much!

**Comment by julianschiavo** [comment]
I've had to blacklist SystemUIServer, all menu bar apps, + Dictation and stuff which don't use SystemUIServer to display icons.

**Comment by w0lfschild** [comment]
This should be fixed in the latest builds. Check for updates in mySIMBL.
