### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by simsinght** [w0lfschild/DoctorDark#3]
I really just wanted to use this for the Messages app because it's so bright.

But the main background doesn't turn dark despite the bundle. Is there a way to change it manually, or are you planning on implementing it?

**Comment by w0lfschild** [comment]
I'll look into this at some point.

**Comment by jakobsperry** [comment]
I would love this change too

**Comment by w0lfschild** [comment]
Unfortunately this doesn't seem like something I know how to implement. :weary:

**Comment by simsinght** [comment]
Aww man that sucks. I tried playing around with Theme Engine to see if I could change the background, but that also didn't pan out.

**Comment by simsinght** [comment]
comes vanilla with macOS mojave
