### ISSUE TITLE
Dark Theme in Finder?

### ISSUE THREAD

**Issue by kamontat** [w0lfschild/DoctorDark#7]
This Repository not support dark in finder?

**Comment by w0lfschild** [comment]
Correct. It would probably take quite a lot of work to get a decent looking Finder implementation.

It is something that I'd like to eventually add along with dark theme for the Messages app. No ETA though, sorry.

**Comment by w0lfschild** [comment]
I've put out an initial build with pretty decent support for Finder. Check for it in mySIMBL.
